### ISSUE TITLE
How to Generate for an Existing Face?

### ISSUE THREAD

**Issue by c1a1o1** [afruehstueck/insetGAN#5]
Multimodal Body Generation for an Existing Face.
For each face generated by the pretrained FFHQ model (middle
column), we use joint optimization to generate three different bodies while maintaining the facial identities from the input faces

**Comment by afruehstueck** [comment]
In order to use a particular face, you either handpick a face from randomly sampled faces from the generator, or you use an inversion or encoding strategy to find a latent space representation of your target face. You can check [e4e](https://github.com/omertov/encoder4editing) for fast image encoding, for example.
